language: python
sudo: false

python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"

env:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=master

matrix:
    include:
      - { python: "3.3", env: TOX_ENV=py33-django-18 }
      - { python: "3.5", env: TOXENV=lint }
      - { python: "3.5", env: TOXENV=docs }

    exclude:
      # Django support for different python versions reference
      # https://docs.djangoproject.com/en/dev/faq/install/#faq-python-version-support
      - { python: "2.7", env: DJANGO=2.0 }
      - { python: "2.7", env: DJANGO=master }
      - { python: "3.4", env: DJANGO=master } # py34 this will become unsupported for 2.1
      - { python: "3.6", env: DJANGO=1.9 }
      - { python: "3.6", env: DJANGO=1.10 }

install: pip install tox tox-travis
script: tox
cache: pip
